version: '3.3'

services:
  ctfd:
    container_name: pwncollege_CTFd
    image: pwncollege_ctfd
    user: root
    restart: always
    environment:
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=mysql+pymysql://ctfd:ctfd@db/ctfd
      - REDIS_URL=redis://cache:6379
      - WORKERS=1
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=-
      - ERROR_LOG=-
      - REVERSE_PROXY=true
      - PWN_COLLEGE_INSTANCE=pwncollege
      - HOST_DATA_PATH=/opt/pwncollege/.data
      - SECRET_KEY=-
      - BINARY_NINJA_API_KEY=-
      - VIRTUAL_HOST=ctf.seclab.engineering.osu.edu
      - VIRTUAL_PORT=8000
      # - LETSENCRYPT_HOST=
    volumes:
      - .data/CTFd/logs:/var/log/CTFd
      - .data/CTFd/uploads:/var/uploads
      - ./CTFd:/opt/CTFd
      - ./CTFd-pwn-college-plugin:/opt/CTFd/CTFd/plugins/CTFd-pwn-college-plugin
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - .data/challenges:/challenges:ro
    depends_on:
      - db
      # - home_daemon
    networks:
        default:
        internal:

  db:
    container_name: pwncollege_db
    image: mariadb:10.4.12
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=ctfd
      - MYSQL_USER=ctfd
      - MYSQL_PASSWORD=ctfd
      - MYSQL_DATABASE=ctfd
    volumes:
      - .data/mysql:/var/lib/mysql
    networks:
        internal:
    # This command is required to set important mariadb defaults
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]

  cache:
    container_name: pwncollege_cache
    image: redis:4
    restart: always
    volumes:
      - .data/redis:/data
    networks:
        internal:

  # home_daemon:
  #   build: home_daemon
  #   user: root
  #   restart: always
  #   privileged: true
  #   volumes:
  #     - type: bind
  #       source: .data/homes
  #       target: /homes
  #       bind:
  #           propagation: shared
  #   networks:
  #       internal:

networks:
    default:
    internal:
        internal: true
